/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apocalipsis.nosafehaven.frontend;

import javax.swing.JOptionPane;

/**
 *
 * @author cristina
 */
public class JDialogServidor extends javax.swing.JDialog {

    private int puerto;
    private boolean confirmado = false;

    /**
     * Creates new form JDialogCliente
     */
    public JDialogServidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public int getPuerto() {
        return puerto;
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        botonListoConexion = new javax.swing.JButton();
        puertoTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 360));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(630, 360));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 360));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 360));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(630, 360));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(630, 360));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        botonListoConexion.setBackground(new java.awt.Color(204, 204, 204));
        botonListoConexion.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        botonListoConexion.setForeground(new java.awt.Color(204, 0, 0));
        botonListoConexion.setText("COMENZAR");
        botonListoConexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListoConexionMouseClicked(evt);
            }
        });
        botonListoConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListoConexionActionPerformed(evt);
            }
        });
        jPanel2.add(botonListoConexion);
        botonListoConexion.setBounds(60, 100, 148, 41);

        puertoTextField.setBackground(new java.awt.Color(204, 204, 204));
        puertoTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        puertoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        puertoTextField.setText("5000");
        puertoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puertoTextFieldMouseClicked(evt);
            }
        });
        jPanel2.add(puertoTextField);
        puertoTextField.setBounds(90, 50, 87, 30);

        jLabel17.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Puerto");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(110, 20, 60, 23);

        jLayeredPane1.add(jPanel2);
        jPanel2.setBounds(170, 130, 280, 160);

        jLabel15.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("NO SAFE HAVEN");
        jLayeredPane1.add(jLabel15);
        jLabel15.setBounds(130, 30, 378, 59);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo1.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 350);

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SERVIDOR");
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(530, 320, 60, 16);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puertoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puertoTextFieldMouseClicked
        puertoTextField.setText("");
    }//GEN-LAST:event_puertoTextFieldMouseClicked

    private void botonListoConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListoConexionActionPerformed
        try {
            int port = Integer.parseInt(puertoTextField.getText());

            if (port < 1024 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Puerto fuera de rango (1024–65535)");
                return;
            }
            puerto = port;
            confirmado = true;

            dispose();  // Cierra el JDialog

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Puerto inválido");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al iniciar el servidor: " + ex.getMessage());
        }
    }//GEN-LAST:event_botonListoConexionActionPerformed

    private void botonListoConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListoConexionMouseClicked
        //esperarInicioCliente();
    }//GEN-LAST:event_botonListoConexionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogServidor dialog = new JDialogServidor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonListoConexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField puertoTextField;
    // End of variables declaration//GEN-END:variables
}
